### ISSUE TITLE
Allow changing the options for a specific toast

### ISSUE THREAD

**Issue by elie222** [chrismbeckett/meteor-toastr#5]
I'd like one of my toasts to only be closed on a click, but the others to be closed automatically. This doesn't seem easily possible at the moment.

This is how you do it using the regular toastr js, but doesn't seem possible with this package:
https://github.com/CodeSeven/toastr/issues/264
toastr.warning(
  "OH NOES",
  "Important Notice:",
  {
    "closeButton": true,
    "positionClass": "toast-top-center",
    "timeOut": "0",
    "extendedTimeOut": "0",
  })

**Comment by chrismbeckett** [comment]
Well, other than the fact that the lastest Toastr is v2.1.1 and my package is still at v2.1.0, it is the native Toastr.js library, it is just wrapped to package for Meteor. If you can do it with Toastr, you can do it with my package? This is not a port, it is the exact same JavaScript library you would find on the Toastr site. If you want to try it directly, create a client/lib folder in your application, and download the Toastr.js file into that folder and just use the native Toastr library directly.
